/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";

const Pyramid = (props) => {
  const { nodes, materials } = useGLTF("models/illusion_cube.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[0, 70.796, 0]}
          scale={1.168}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle.geometry}
          material={nodes.Rectangle.material}
          position={[0, 45, 1]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_1.geometry}
          material={nodes.Rectangle_1.material}
          position={[0, 0, 1]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.地面.geometry}
          material={nodes.地面.material}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[-448.405, 522.637, 742.85]}
          rotation={[-0.542, -0.48, -0.271]}
        />
        <directionalLight
          intensity={0.7}
          decay={2}
          rotation={[0.946, 0.376, -1.312]}
        />
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[-1104.448, 393.12, -423.389]}
          rotation={[-3.052, -1.405, -3.054]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("models/illusion_cube.glb");

export default Pyramid;
